#!/usr/bin/env node
// Builds a throwaway dist for @qr-manager/ui so design-sync's converter has a
// real entry + .d.ts tree to read. The package itself ships raw src/ via
// subpath exports and has no build; everything written here is gitignored and
// regenerated on every sync.
//
//   packages/ui/ds-dist/index.js    esbuild bundle (react family external)
//   packages/ui/ds-dist/**/*.d.ts   tsc declaration emit
//   packages/ui/index.d.ts           types entry (dts.mjs looks for it here)
//   packages/ui/ds-dist/styles.css  compiled Tailwind v4 stylesheet
//
// Run: node .design-sync/build-dist.mjs
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, symlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PKG = join(REPO, 'packages/ui');
const SRC = join(PKG, 'src');
const OUT = join(PKG, 'ds-dist');

// reui/badge.tsx exports a second `Badge` that collides with components/badge.tsx.
// It stays bundled (data-grid-column-filter imports it) but is not re-exported.
const SKIP = new Set([join(SRC, 'components/reui/badge.tsx')]);

const walk = (d, out = []) => {
  for (const n of readdirSync(d)) {
    const p = join(d, n);
    statSync(p).isDirectory() ? walk(p, out) : /\.tsx$/.test(p) && out.push(p);
  }
  return out;
};

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const files = walk(join(SRC, 'components')).filter((p) => !SKIP.has(p)).sort();
const barrel = files
  .map((p) => `export * from ${JSON.stringify('./' + relative(PKG, p).replace(/\.tsx$/, ''))};`)
  .join('\n');
writeFileSync(join(PKG, 'ds-entry.ts'), `// generated by .design-sync/build-dist.mjs — do not edit\n${barrel}\n`);
console.error(`» barrel: ${files.length} component files`);

// ── JS bundle ────────────────────────────────────────────────────────────
const esbuild = join(REPO, '.ds-sync/node_modules/.bin/esbuild');
execFileSync(esbuild, [
  join(PKG, 'ds-entry.ts'),
  '--bundle', '--format=esm', '--platform=browser', '--jsx=automatic',
  `--tsconfig=${join(PKG, 'tsconfig.json')}`,
  '--external:react', '--external:react-dom', '--external:react/jsx-runtime',
  '--external:react-dom/client', '--external:react-is', '--external:scheduler',
  '--log-level=error',
  `--outfile=${join(OUT, 'index.js')}`,
], { stdio: 'inherit', cwd: PKG });
console.error('» bundled ds-dist/index.js');

// ── declaration emit ─────────────────────────────────────────────────────
writeFileSync(join(PKG, 'ds-tsconfig.json'), JSON.stringify({
  extends: './tsconfig.json',
  compilerOptions: {
    noEmit: false, declaration: true, emitDeclarationOnly: true,
    jsx: 'react-jsx', skipLibCheck: true, outDir: './ds-dist', rootDir: '.',
    // The shared base sets incremental + a package-level tsBuildInfoFile. Left
    // alone, the second sync sees "up to date" and emits nothing (and this run
    // would trample the buildinfo `pnpm typecheck` relies on).
    incremental: false, tsBuildInfoFile: null, noEmitOnError: false,
  },
  include: ['ds-entry.ts', 'src'],
}, null, 2) + '\n');
try {
  execFileSync(join(REPO, 'node_modules/.bin/tsc'), ['-p', join(PKG, 'ds-tsconfig.json')], {
    stdio: 'inherit', cwd: PKG,
  });
} catch {
  console.error('! tsc reported errors — declarations emitted anyway (checked below)');
}
writeFileSync(join(PKG, 'index.d.ts'), `export * from "./ds-dist/ds-entry";\n`);
console.error('» emitted .d.ts tree + index.d.ts');

// ── compiled Tailwind v4 stylesheet ──────────────────────────────────────
// The package ships src/styles/globals.css, a Tailwind *source* file
// (@import "tailwindcss"), not a stylesheet. Compile it so cfg.cssEntry has
// real CSS; @source globs inside it resolve relative to the source file.
execFileSync('pnpm', ['dlx', '@tailwindcss/cli@4.3.3', '-i', '../../.design-sync/ds-styles.css', '-o', 'ds-dist/styles.css'], {
  stdio: 'inherit', cwd: PKG, env: { ...process.env, COREPACK_ENABLE_STRICT: '0' },
});

// fontsource emits url(./files/*.woff2) — copy the files next to the css so
// the converter can harvest them into fonts/.
mkdirSync(join(OUT, 'files'), { recursive: true });
for (const fam of ['@fontsource-variable/geist-mono', '@fontsource-variable/jetbrains-mono']) {
  const dir = join(PKG, 'node_modules', fam, 'files');
  for (const f of readdirSync(dir)) {
    if (/\.woff2$/.test(f)) cpSync(join(dir, f), join(OUT, 'files', f));
  }
}
console.error('» compiled styles.css + copied font files');

// ── node_modules view for the converter ──────────────────────────────────
// @qr-manager/ui doesn't depend on react-dom (it's a peer of the apps), but
// the converter vendors React + ReactDOM into _vendor/. Mirror the package's
// own node_modules and add react-dom from the frontend, which pins the same
// 19.2.8 as packages/ui/node_modules/react.
const NM = join(REPO, '.design-sync/.cache/nm/node_modules');
rmSync(NM, { recursive: true, force: true });
mkdirSync(NM, { recursive: true });
const link = (from, to) => { mkdirSync(dirname(to), { recursive: true }); symlinkSync(from, to); };
for (const n of readdirSync(join(PKG, 'node_modules'))) {
  if (n.startsWith('@')) {
    for (const s2 of readdirSync(join(PKG, 'node_modules', n))) link(join(PKG, 'node_modules', n, s2), join(NM, n, s2));
  } else link(join(PKG, 'node_modules', n), join(NM, n));
}
for (const n of ['react-dom', 'scheduler']) {
  const from = join(REPO, 'apps/frontend/node_modules', n);
  if (existsSync(from) && !existsSync(join(NM, n))) link(from, join(NM, n));
}
console.error(`» node_modules view at ${relative(REPO, NM)}`);
