import { defineConfig } from "eslint/config";

import { baseConfig } from "@qr-manager/eslint-config/base";
import { reactConfig } from "@qr-manager/eslint-config/react";

export default defineConfig(
  {
    // Generated by `.design-sync/build-dist.mjs` and gitignored, but the root
    // .gitignore's `packages/ui/` prefixes do not match against this config's
    // own base path, so they have to be named again here.
    ignores: ["dist/**", "ds-dist/**", "ds-entry.ts", "index.d.ts"],
  },
  baseConfig,
  reactConfig,
);
