/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as AppSettingsPathRouteImport } from './routes/_app/settings/$path'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsPathRoute = AppSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/$path': typeof AuthPathRoute
  '/settings/$path': typeof AppSettingsPathRoute
}
export interface FileRoutesByTo {
  '/auth/$path': typeof AuthPathRoute
  '/': typeof AppIndexRoute
  '/settings/$path': typeof AppSettingsPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/$path': typeof AppSettingsPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/$path' | '/settings/$path'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/$path' | '/' | '/settings/$path'
  id: '__root__' | '/_app' | '/auth/$path' | '/_app/' | '/_app/settings/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthPathRoute: typeof AuthPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings/$path': {
      id: '/_app/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof AppSettingsPathRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsPathRoute: typeof AppSettingsPathRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppSettingsPathRoute: AppSettingsPathRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthPathRoute: AuthPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
