/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCodesRouteImport } from './routes/_app/codes'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppCodesIndexRouteImport } from './routes/_app/codes/index'
import { Route as AppCodesCodeIdRouteImport } from './routes/_app/codes/$codeId'
import { Route as AppCodesNewRouteImport } from './routes/_app/codes/new'
import { Route as AppSettingsPathRouteImport } from './routes/_app/settings/$path'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCodesRoute = AppCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AppRoute,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppCodesIndexRoute = AppCodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCodesRoute,
} as any)
const AppCodesCodeIdRoute = AppCodesCodeIdRouteImport.update({
  id: '/$codeId',
  path: '/$codeId',
  getParentRoute: () => AppCodesRoute,
} as any)
const AppCodesNewRoute = AppCodesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCodesRoute,
} as any)
const AppSettingsPathRoute = AppSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/setup': typeof SetupRoute
  '/codes': typeof AppCodesRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/codes/$codeId': typeof AppCodesCodeIdRoute
  '/codes/new': typeof AppCodesNewRoute
  '/settings/$path': typeof AppSettingsPathRoute
  '/codes/': typeof AppCodesIndexRoute
}
export interface FileRoutesByTo {
  '/setup': typeof SetupRoute
  '/auth/$path': typeof AuthPathRoute
  '/': typeof AppIndexRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/codes/$codeId': typeof AppCodesCodeIdRoute
  '/codes/new': typeof AppCodesNewRoute
  '/settings/$path': typeof AppSettingsPathRoute
  '/codes': typeof AppCodesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/_app/codes': typeof AppCodesRouteWithChildren
  '/auth/$path': typeof AuthPathRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/codes/$codeId': typeof AppCodesCodeIdRoute
  '/_app/codes/new': typeof AppCodesNewRoute
  '/_app/settings/$path': typeof AppSettingsPathRoute
  '/_app/codes/': typeof AppCodesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/codes'
    | '/auth/$path'
    | '/admin/users'
    | '/codes/$codeId'
    | '/codes/new'
    | '/settings/$path'
    | '/codes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setup'
    | '/auth/$path'
    | '/'
    | '/admin/users'
    | '/codes/$codeId'
    | '/codes/new'
    | '/settings/$path'
    | '/codes'
  id:
    | '__root__'
    | '/_app'
    | '/setup'
    | '/_app/codes'
    | '/auth/$path'
    | '/_app/'
    | '/_app/admin/users'
    | '/_app/codes/$codeId'
    | '/_app/codes/new'
    | '/_app/settings/$path'
    | '/_app/codes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  AuthPathRoute: typeof AuthPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/codes': {
      id: '/_app/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof AppCodesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/codes/': {
      id: '/_app/codes/'
      path: '/'
      fullPath: '/codes/'
      preLoaderRoute: typeof AppCodesIndexRouteImport
      parentRoute: typeof AppCodesRoute
    }
    '/_app/codes/$codeId': {
      id: '/_app/codes/$codeId'
      path: '/$codeId'
      fullPath: '/codes/$codeId'
      preLoaderRoute: typeof AppCodesCodeIdRouteImport
      parentRoute: typeof AppCodesRoute
    }
    '/_app/codes/new': {
      id: '/_app/codes/new'
      path: '/new'
      fullPath: '/codes/new'
      preLoaderRoute: typeof AppCodesNewRouteImport
      parentRoute: typeof AppCodesRoute
    }
    '/_app/settings/$path': {
      id: '/_app/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof AppSettingsPathRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCodesRouteChildren {
  AppCodesCodeIdRoute: typeof AppCodesCodeIdRoute
  AppCodesNewRoute: typeof AppCodesNewRoute
  AppCodesIndexRoute: typeof AppCodesIndexRoute
}

const AppCodesRouteChildren: AppCodesRouteChildren = {
  AppCodesCodeIdRoute: AppCodesCodeIdRoute,
  AppCodesNewRoute: AppCodesNewRoute,
  AppCodesIndexRoute: AppCodesIndexRoute,
}

const AppCodesRouteWithChildren = AppCodesRoute._addFileChildren(
  AppCodesRouteChildren,
)

interface AppRouteChildren {
  AppCodesRoute: typeof AppCodesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppSettingsPathRoute: typeof AppSettingsPathRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCodesRoute: AppCodesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppSettingsPathRoute: AppSettingsPathRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  AuthPathRoute: AuthPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
